# Generated by Django 5.2.8 on 2025-12-05 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_assets', '0004_sharingscope_check_in_virtual_labs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_assets.baseasset')),
                ('file', models.FileField(unique=True, upload_to='files/')),
            ],
            bases=('base_assets.baseasset',),
        ),
    ]
