# Generated by Django 5.2.8 on 2025-12-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAssetCreationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to='files/')),
                ('request_creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['request_creation_date'],
            },
        ),
    ]
