# Generated by Django 5.1.7 on 2025-04-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseasset',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
