# Generated by Django 5.1.7 on 2025-09-18 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_assets', '0002_alter_baseasset_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ]

    operations = [
        migrations.CreateModel(
            name='SharingScope',
            fields=[
                ('slug', models.SlugField(
                    primary_key=True, serialize=False, unique=True
                    )),
                ('title', models.CharField(max_length=255)),
                ('label', models.CharField(
                    choices=[('virtual_lab', 'Virtual Lab'),
                             ('community', 'Community')], max_length=100
                    )),
                ],
            ),
        migrations.AddField(
            model_name='baseasset',
            name='shared_with_users',
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL
                ),
            ),
        migrations.AddField(
            model_name='baseasset',
            name='shared_with_scopes',
            field=models.ManyToManyField(
                blank=True, to='base_assets.sharingscope'
                ),
            ),
        ]
