# Generated by Django 5.1.7 on 2025-09-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_assets',
         '0003_sharingscope_baseasset_shared_with_users_and_more'),
        ('virtual_labs', '0004_virtuallablabel_virtuallab_labels'),
        ]

    operations = [
        migrations.AddField(
            model_name='sharingscope',
            name='check_in_virtual_labs',
            field=models.ManyToManyField(
                blank=True, related_name='checked_sharing_scopes',
                to='virtual_labs.virtuallab'
                ),
            ),
        migrations.AddField(
            model_name='sharingscope',
            name='show_in_virtual_labs',
            field=models.ManyToManyField(
                blank=True, related_name='visible_sharing_scopes',
                to='virtual_labs.virtuallab'
                ),
            ),
        ]
