# Generated by Django 5.1.7 on 2025-04-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtuallab',
            name='container_image',
            field=models.CharField(blank=True, help_text='Container image of the virtual lab', max_length=384),
        ),
        migrations.AlterField(
            model_name='virtuallab',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
