# Generated by Django 5.1.7 on 2025-09-04 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_labs', '0003_virtuallab_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualLabLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The display name of the label.', max_length=255, unique=True)),
                ('color', models.CharField(help_text='Color in hex format (e.g. #FFFFFF).', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex code, e.g., #FFF or #FFFFFF.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
            ],
        ),
        migrations.AddField(
            model_name='virtuallab',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='VirtualLabs', to='virtual_labs.virtuallablabel'),
        ),
    ]
