# Generated by Django 6.0.2 on 2026-05-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_labs', '0004_virtuallablabel_virtuallab_labels'),
        ]

    operations = [
        migrations.AlterField(
            model_name='virtuallab',
            name='deployment_url',
            field=models.URLField(
                blank=True, help_text='URL of the virtual lab deployment',
                max_length=1000, verbose_name='URL'
                ),
            ),
        ]
