# Generated by Django 6.0.2 on 2026-05-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_labs', '0005_alter_virtuallab_deployment_url'),
        ]

    operations = [
        migrations.AddField(
            model_name='virtuallab',
            name='binder_ref',
            field=models.CharField(
                blank=True,
                help_text='Binder ref (e.g. gh/NaaVRE/vl-openlab/HEAD)',
                max_length=500
                ),
            ),
        ]
