# Generated by Django 6.0.2 on 2026-06-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_labs', '0006_virtuallab_binder_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtuallab',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtuallab',
            name='pinned_order',
            field=models.IntegerField(default=-1),
        ),
    ]
