# Generated by Django 6.0.6 on 2026-06-11 21:47

import django.core.serializers.json
from django.db import migrations
import django_pydantic_field.compat.django
import django_pydantic_field.fields

import virtual_labs.models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_labs', '0007_virtuallab_is_pinned_virtuallab_pinned_order'),
        ]

    operations = [
        migrations.AddField(
            model_name='virtuallab',
            name='additional_actions',
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True, config=None, default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    list, (virtual_labs.models.AdditionalAction,)
                    )
                ),
            ),
        ]
