# Generated by Django 6.0.6 on 2026-06-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_labs', '0008_virtuallab_additional_actions'),
        ]

    operations = [
        migrations.AddField(
            model_name='virtuallab',
            name='long_description',
            field=models.TextField(
                blank=True,
                help_text='Markdown-formatted description of the virtual lab'
                ),
            ),
        migrations.AlterField(
            model_name='virtuallab',
            name='description',
            field=models.TextField(
                blank=True, help_text='Short description of the virtual lab'
                ),
            ),
        ]
