# Generated by Django 6.0.6 on 2026-06-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binder_environments', '0001_initial'),
        ('virtual_labs', '0009_virtuallab_long_description_and_more'),
        ]

    operations = [
        migrations.AlterField(
            model_name='virtuallab',
            name='binder_environment',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='binder_environments.binderenvironment'
                ),
            ),
        ]
