# Generated by Django 5.1.2 on 2024-10-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_assets', '0001_initial'),
        ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('baseasset_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True, primary_key=True, serialize=False,
                    to='base_assets.baseasset'
                    )),
                ('source_url', models.URLField(
                    blank=True,
                    help_text='URL workflows source file in naavrewf format',
                    verbose_name='source URL'
                    )),
                ('run_url', models.URLField(
                    blank=True,
                    help_text='URL of the workflows execution (for example on argo)',
                    verbose_name='run URL'
                    )),
                ('status', models.CharField(
                    blank=True,
                    help_text='Workflow status (example: Succeeded)',
                    max_length=50
                    )),
                ('progress', models.CharField(
                    blank=True, help_text='Workflow progress (example: 5/5)',
                    max_length=50
                    )),
                ],
            bases=('base_assets.baseasset',),
            ),
        ]
