# Generated by Django 6.0.6 on 2026-06-23 16:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ]

    operations = [
        migrations.CreateModel(
            name='BinderEnvironment',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4, editable=False, primary_key=True,
                    serialize=False
                    )),
                ('binder_ref', models.CharField(
                    help_text='Binder ref (e.g. gh/NaaVRE/vl-openlab/HEAD)',
                    max_length=500, unique=True
                    )),
                ('container_image', models.CharField(
                    blank=True,
                    help_text='Container image of the binder environment',
                    max_length=384
                    )),
                ('pre_pull', models.BooleanField(default=False)),
                ],
            ),
        ]
