# Generated by Django 5.1.7 on 2025-04-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_cells', '0002_alter_cell_container_image_alter_cell_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='asname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
