# Generated by Django 5.1.7 on 2025-07-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_cells', '0004_alter_baseimage_build_alter_baseimage_runtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='default_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
