# Generated by Django 5.1.7 on 2025-09-05 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_cells', '0005_alter_param_default_value'),
        ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='next_version',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='workflow_cells.cell'
                ),
            ),
        migrations.AddField(
            model_name='cell',
            name='version',
            field=models.IntegerField(default=1),
            ),
        ]
