# Generated by Django 6.0 on 2026-01-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_cells', '0006_cell_next_version_cell_version'),
        ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='is_draft',
            field=models.BooleanField(default=False),
            ),
        migrations.AlterField(
            model_name='cell',
            name='container_image',
            field=models.CharField(
                blank=True,
                help_text='Containerized cell image (example: ghcr.io/me/my-naavre-cells/my-cell-1:49c621b)',
                max_length=384, null=True
                ),
            ),
        ]
