# Generated by Django 6.0 on 2026-05-08 12:57

from django.db import migrations, models


def create_versions_collections(apps, schema_editor):
    Asset = apps.get_model("workflow_cells", "Cell")
    VersionsCollection = apps.get_model("workflow_cells", "CellVersionsCollection")
    for asset in Asset.objects.all():
        has_previous_version = asset.cell_set.exists()
        if not has_previous_version:
            collection = VersionsCollection.objects.create()
            while asset is not None:
                collection.versions.add(asset)
                asset = asset.next_version


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_cells', '0007_cell_is_draft_alter_cell_container_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellVersionsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versions', models.ManyToManyField(to='workflow_cells.cell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_versions_collections),
        migrations.RemoveField(
            model_name='cell',
            name='next_version',
        ),
    ]
