# Generated by Django 6.0 on 2026-05-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_cells', '0007_cell_is_draft_alter_cell_container_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='next_version',
        ),
        migrations.CreateModel(
            name='CellVersionsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versions', models.ManyToManyField(to='workflow_cells.cell')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
