# Generated by Django 6.0.2 on 2026-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_cells',
         '0008_remove_cell_next_version_cellversionscollection'),
        ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='template_format',
            field=models.CharField(
                blank=True, choices=[('v1', 'v1'), ('v2', 'v2')], default='v1',
                max_length=2, null=True
                ),
            ),
        ]
