# Generated by Django 6.0.6 on 2026-08-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_cells', '0009_cell_template_format'),
        ]

    operations = [
        migrations.CreateModel(
            name='CellContainerizationJob',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID'
                    )),
                ('html_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(
                    choices=[('queued', 'Queued'),
                             ('in_progress', 'In progress'),
                             ('completed', 'Completed'),
                             ('waiting', 'Waiting'),
                             ('requested', 'Requested'),
                             ('pending', 'Pending')], max_length=11
                    )),
                ('conclusion', models.CharField(
                    blank=True,
                    choices=[('success', 'Success'), ('failure', 'Failure'),
                             ('neutral', 'Neutral'),
                             ('cancelled', 'Cancelled'),
                             ('skipped', 'Skipped'),
                             ('timed_out', 'Timed out'),
                             ('action_required', 'Action required')],
                    max_length=15, null=True
                    )),
                ],
            ),
        migrations.AddField(
            model_name='cell',
            name='containerization_job',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='workflow_cells.cellcontainerizationjob'
                ),
            ),
        ]
