# Generated by Django 6.0.6 on 2026-08-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_assets', '0004_sharingscope_check_in_virtual_labs_and_more'),
        ('workflow_cells',
         '0010_cellcontainerizationjob_cell_containerization_job'),
        ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='containerization_workflow_id',
            field=models.UUIDField(blank=True, null=True),
            ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('containerization_job__isnull', True),
                        ('containerization_workflow_id__isnull', True)
                        ), models.Q(
                        ('containerization_job__isnull', False),
                        ('containerization_workflow_id__isnull', False)
                        ), _connector='OR'
                    ),
                name='workflow_cells_cell_containerization_job_and_workflow_id_null_together'
                ),
            ),
        ]
