# Generated by Django 6.1 on 2026-08-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_assets', '0004_sharingscope_check_in_virtual_labs_and_more'),
        ('workflow_cells', '0011_cell_containerization_workflow_id_and_more'),
        ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cell',
            name='workflow_cells_cell_containerization_job_and_workflow_id_null_together',
            ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('containerization_job__isnull', True),
                        ('containerization_workflow_id__isnull', True)
                        ), models.Q(
                        ('containerization_job__isnull', False),
                        ('containerization_workflow_id__isnull', False)
                        ), _connector='OR'
                    ),
                name='workflow_cell_containerization_job_and_workflow_null_together'
                ),
            ),
        ]
