# Generated by Django 5.1.7 on 2025-05-16 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_lab_instances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ]

    operations = [
        migrations.RemoveField(
            model_name='virtuallabinstance',
            name='username',
            ),
        migrations.AddField(
            model_name='virtuallabinstance',
            name='date',
            field=models.DateTimeField(
                auto_now_add=True, default='2025-05-16T14:10:06'
                ),
            preserve_default=False,
            ),
        migrations.AddField(
            model_name='virtuallabinstance',
            name='user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
                ),
            ),
        ]
