# Generated by Django 5.2.8 on 2025-12-05 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_assets', '0001_initial'),
        ]

    operations = [
        migrations.CreateModel(
            name='WorkflowFile',
            fields=[
                ('fileasset_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True, primary_key=True, serialize=False,
                    to='file_assets.fileasset'
                    )),
                ('version', models.IntegerField(default=1)),
                ('next_version', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='workflow_files.workflowfile'
                    )),
                ],
            options={
                'abstract': False,
                },
            bases=('file_assets.fileasset', models.Model),
            ),
        ]
