# Generated by Django 6.0 on 2026-05-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowfile',
            name='next_version',
        ),
        migrations.CreateModel(
            name='WorkflowFileVersionsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versions', models.ManyToManyField(to='workflow_files.workflowfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
