# Generated by Django 6.0 on 2026-05-08 12:57

from django.db import migrations, models


def create_versions_collections(apps, schema_editor):
    Asset = apps.get_model("notebook_files", "NotebookFile")
    VersionsCollection = apps.get_model("notebook_files", "NotebookFileVersionsCollection")
    for asset in Asset.objects.all():
        has_previous_version = asset.notebookfile_set.exists()
        if not has_previous_version:
            collection = VersionsCollection.objects.create()
            while asset is not None:
                collection.versions.add(asset)
                asset = asset.next_version


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookFileVersionsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versions', models.ManyToManyField(to='notebook_files.notebookfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_versions_collections),
        migrations.RemoveField(
            model_name='notebookfile',
            name='next_version',
            ),
        ]
